version: '3.3'

services:
  crypto-wallet:
    build: ./
    command: ./wait-for-postgres.sh db ./crypto-wallet
    ports:
      - 8000:8000
    depends_on:
      - db
    environment:
      - DB_PASSWORD=123123

  db:
    restart: always
    image: postgres
    volumes:
      - ./.database/postgres/data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=123123
    ports:
      - 5432:5432